# Development docker-compose for Next.js 15 with Server Components

services:
  # PostgreSQL database for development
  postgres:
    image: postgres:16-alpine
    container_name: otter-trip-postgres-dev
    restart: unless-stopped
    env_file:
      - .env.local
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=otter_trip_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-postgres} -d otter_trip_dev']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Next.js development server
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: otter-trip-dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app:delegated
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/otter_trip_dev
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-dev-secret-key}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev

volumes:
  postgres_dev_data:
    driver: local
