services:
  # PostgreSQL database
  postgres:
    image: postgres:16-alpine
    container_name: otter-trip-postgres
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=otter_trip_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-postgres} -d otter_trip_prod']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - proxy-network

  # Main application
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: otter-trip-app
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD}@postgres:5432/otter_trip_prod?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://0.0.0.0:3000/']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - proxy-network
    # No ports exposed - only accessible through proxy

  # Nginx proxy with integrated Certbot
  nginx-proxy:
    build:
      context: ./docker/nginx-proxy
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - .env.production
    environment:
      # Single domain configuration
      - DOMAIN=${DOMAIN}
      - UPSTREAM_HOST=app
      - UPSTREAM_PORT=3000
      - SSL_EMAIL=${SSL_EMAIL}
      - STAGING=${STAGING:-false}
      # OR multiple domains (comma-separated)
      # Format: domain:upstream_host:upstream_port,domain2:upstream_host2:upstream_port2
      # - AUTO_DOMAINS=example.com:app:3000,api.example.com:api:8080
    volumes:
      # Persistent storage for certificates
      - letsencrypt:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
      # Logs
      - ./logs/nginx:/var/log/nginx
      - ./logs/letsencrypt:/var/log/letsencrypt
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - proxy-network

volumes:
  postgres_data:
    driver: local
  letsencrypt:
    driver: local
  certbot-webroot:
    driver: local

networks:
  proxy-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
